version: '3.8'

services:
  
  db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    container_name: db
    ports:
      - '5432:5432'
    networks:
      - elk
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0 --reload';  
    volumes:
      - .:/app
    ports:
      - 80:8000
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"
    networks:
      - elk
      
  traefik:
    image: traefik:v2.9.6
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - elk
      
  # front-end:
  #   build: 
  #     context: ./front-end
  #     dockerfile: ../Dockerfile.front-end
  #   ports:
  #     - "3011:3011"
  #   environment:
  #     - WDS_SOCKET_HOST=127.0.0.1 
  #     - CHOKIDAR_USEPOLLING=true
  #     - WATCHPACK_POLLING=true 
  #     - NODE_ENV=development
  #   volumes:
  #     - ./front-end:/app
  #     - /app/node_modules
  #   networks:
  #     - elk

networks:
  elk:
    name: fastapi_network
    driver: bridge

volumes:
  postgres_data: