FROM node:21.7-alpine3.18

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN apk add --no-cache python3 make g++ && \
    npm install --legacy-peer-deps

# Copy the local code to the container
COPY . .

# Expose the port the app runs on
EXPOSE 3011

# Command to run the application
CMD ["npm", "start"]