CREATE TABLE "Doituong" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_name" varchar,
  "CMND" varchar,
  "CCCD" varchar,
  "Image" varchar,
  "Ngaysinh" date,
  "Gioitinh" boolean,
  "Quequan" varchar,
  "Thongtinbosung" varchar,
  "SDT" varchar,
  "KOL" boolean,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "color_id" int
);

CREATE TABLE "model_has_tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "model_id" int,
  "tags_id" int
);

CREATE TABLE "UID" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY,
  "uid" varchar,
  "name" varchar,
  "reaction" int,
  "SDT" varchar,
  "trangthai_id" int,
  "type_id" int,
  "ghichu" varchar,
  "Vaiao" boolean,
  "created_at" date,
  "updated_at" date,
  PRIMARY KEY ("id", "uid")
);

CREATE TABLE "Doituong_UID" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "doituong_id" int,
  "uid" varchar,
  "Moiquanhe_id" int,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "quantrivien" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid_facebook" varchar,
  "uid" varchar,
  "Moiquanhe_id" int,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "trangthai" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trangthai_name" varchar,
  "color_id" int,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "tinhchat" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tinhchat_name" varchar,
  "color_id" int,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "color" (
  "color_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "color" varchar
);

CREATE TABLE "trangthai_hoinhom" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trangthai_id" int,
  "uid" varchar,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "CTNV" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "CTNV_name" varchar,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "tinhchat_hoinhom" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tinhchat_id" int,
  "uid" varchar,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "type" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "Moiquanhe" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Moiquanhe_name" varchar,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "donvi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "Trichtin" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid" varchar,
  "ghichu_noidung" varchar,
  "nhanxet" varchar,
  "xuly" varchar,
  "uid_vaiao" varchar,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "donvi_hoinhom" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "donvi_id" int,
  "uid" varchar,
  "CTNV_ID" int,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "user_donvi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "donvi_id" int,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "vaiao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid_hoinhom" varchar,
  "uid_vaiao" varchar,
  "andanh" boolean,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "Role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "Permission" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "user_has_permissions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "Permission_id" int,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "user_has_role" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "role" int,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "role_has_permission" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" int,
  "permission_id" int,
  "created_at" date,
  "updated_at" date
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "password" varchar,
  "salt" varchar,
  "active" varchar,
  "created_at" date,
  "updated_at" date
);
