from fastapi import APIRouter
from app.Routes.router_api import (uid, ctnv, moiquanhe, vaiao, user_has_role, trangthai_hoinhom,type,
user, auth, user_donvi, donvi_hoinhom ,trichtin,role_has_permission,role, quantrivien, permission,
user_has_permission, doituong,tags, model_has_tags, doituong_donvi, elasticsearch,
tinhchat_hoinhom, doituong_uid, trangthai, tinhchat, color, donvi, thongke)
api_router = APIRouter()

api_router.include_router(uid.router)
api_router.include_router(user.router)
api_router.include_router(auth.router)
api_router.include_router(user_donvi.router)
api_router.include_router(role_has_permission.router)
api_router.include_router(user_has_permission.router)
api_router.include_router(doituong.router)
api_router.include_router(tags.router)
api_router.include_router(model_has_tags.router)
api_router.include_router(doituong_donvi.router)
api_router.include_router(donvi_hoinhom.router)
api_router.include_router(trichtin.router)
api_router.include_router(tinhchat_hoinhom.router)
api_router.include_router(doituong_uid.router)
api_router.include_router(trangthai.router) 
api_router.include_router(tinhchat.router)
api_router.include_router(moiquanhe.router)
api_router.include_router(ctnv.router)
api_router.include_router(vaiao.router)
api_router.include_router(user_has_role.router)
api_router.include_router(color.router)
api_router.include_router(trangthai_hoinhom.router)
api_router.include_router(type.router)
api_router.include_router(donvi.router)
api_router.include_router(role.router)
api_router.include_router(quantrivien.router)
api_router.include_router(permission.router)
api_router.include_router(thongke.router)
api_router.include_router(elasticsearch.router)