from fastapi import APIRouter
from app.Routes.router_api import (
    administrator,
    status,
    tag,
    task,
    permission,
    relationship,
    role,
    unit,
    individual,
    characteristic,
    group_characteristic,
    group_status,
    individual_unit,
    report,
    unit_group,
    social_account_link,
    individual_social_account,
    individual_tag,
    social_account,
    auth,
    user,
    uid,
    search,
    dashboard,
    account_type,
    user_role,
    user_permission,
    role_permission
)

api_router = APIRouter()

api_router.include_router(administrator)
api_router.include_router(status)
api_router.include_router(tag)
api_router.include_router(task)
api_router.include_router(permission)
api_router.include_router(relationship)
api_router.include_router(role)
api_router.include_router(unit)
api_router.include_router(individual)
api_router.include_router(characteristic)
api_router.include_router(group_characteristic)
api_router.include_router(group_status)
api_router.include_router(individual_unit)
api_router.include_router(report)
api_router.include_router(unit_group)
api_router.include_router(social_account_link)
api_router.include_router(individual_social_account)
api_router.include_router(individual_tag)
api_router.include_router(social_account)
api_router.include_router(auth)
api_router.include_router(user)
api_router.include_router(uid)
api_router.include_router(search)
api_router.include_router(dashboard)
api_router.include_router(account_type)
api_router.include_router(user_role)
api_router.include_router(user_permission)
api_router.include_router(role_permission)